name: lint-pylama

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pylama
        mypy
    - name: Analysing the code with pylama
      run: |
        pylama --skip='tests/*'
    - name: Analysing the code with pylint
      run: |
        pylint modifiable_items_dictionary/
    - name: Analysing the code with mypy
      run: |
        mypy modifiable_items_dictionary/