
name: pytest

on: workflow_call

jobs:
  build:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.7","3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [-f setup.py]; then python setup.py install; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Test and generate coverage report
      run: |
        pytest --cov=tests/ --cov-report=xml --doctest-modules
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        fail_ci_if_error: true